# Generated by Django 3.1.7 on 2021-04-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomapplication', '0007_auto_20210402_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='location',
        ),
    ]
