# Generated by Django 3.1.7 on 2021-04-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomapplication', '0010_contactmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmodel',
            table='contactmodel',
        ),
    ]
