# Generated by Django 3.1.7 on 2021-04-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomapplication', '0011_auto_20210405_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
